
type ErrorTypes = { [errorCode: string]: string }

const FATAL_ERRORS: ErrorTypes = {
    '1000': 'API version does not exist.',
    '1001': 'API version was removed.',
    '1002': 'API class does not exist.',
    '1003': 'API function does not exist.',
    '1004': 'The API keys does not own the privilege to execute this action.',
    '1005': 'The used login token is invalid.',
    '1006': 'The called function is locked.',
    '1007': 'Proxer.me is currently undergoing maintenance.',
    '1008': 'The API is currently undergoing maintenance.'
}

const SERVER_SIDE_ERRORS: ErrorTypes = {
    '2000': 'IP was blocked by firewall.',
    '2001': 'Error while fetching news.',
}

const CLIENT_SIDE_ERRORS: ErrorTypes = {
    '3000': 'Login failed: Missing login credentials.',
    '3001': 'Login failed: Invalid login credentials.',
    '3002': 'Fetching notifications failed: User is not logged in.',
    '3003': 'Fetching userinfo failed: User id does not exist.',
    '3004': 'UCP error: User is not logged in.',
    '3005': 'UCP error: Category does not exist.',
    '3006': 'UCP error: Invalid id.',
    '3007': 'Info error: Invalid id.',
    '3008': 'Setting userinfo failed: Invalid type.',
    '3009': 'Setting userinfo failed: User is not logged in.',
    '3010': 'Setting userinfo failed: Content already exists in list.',
    '3011': 'Setting userinfo failed: Favorite limit exceeded.',
    '3012': 'Login failed: User is already logged in.',
    '3013': 'Login failed: Another user is already logged in.',
    '3014': 'User error: Access to information denied. (This might be caused by not beeing logged in with a user)',
    '3015': 'List error: Category does not exist.',
    '3016': 'List error: Medium does not exist.',
    '3017': 'Media error: Style does not exist.',
    '3018': 'Media error: Entry does not exist.',
    '3019': 'Manga error: Chapter does not exist. (Maybe it simply is not uploaded or linked yet)',
    '3020': 'Anime error: Episode does not exist. (Maybe it simply is not uploaded or linked yet)',
    '3021': 'Anime error: Stream does not exist.',
    '3022': 'UCP error: Episode does not exist.',
    '3023': 'Messages error: User is not logged in.',
    '3024': 'Messages error: Invalid conference. (missing permissions or invalid id)',
    '3025': 'Messages error: Invalid or missing input.',
    '3026': 'Messages error: Invalid or missing message.',
    '3027': 'Messages error: Invalid user.',
    '3028': 'Messages error: User limit exceeded.',
    '3029': 'Messages error: Invalid or missing topic.',
    '3030': 'Messages error: At least one user needs to be added to a conference',
    '3031': 'Chat error: Invalid room.',
    '3032': 'Chat error: Missing permissions.',
    '3033': 'Chat error: Invalid message. (this always corresponds to a specific message id)',
    '3034': 'Chat error: User is not logged in.',
    '3035': 'List error: Invalid language.',
    '3036': 'List error: Invalid type.',
    '3037': 'List error: Invalid id.',
    '3038': 'Login failed: The user has 2FA activated. The secret key needs to be specified.',
    '3039': 'Login failed: The user account got terminated.',
    '3040': 'Login failed: The user account is banned.',
    '3041': 'User error: An internal error occured.',
    '3042': 'Apps error: An empty string was sent.',
    '3043': 'List error: Invalid subject.',
    '3044': 'Forum error: Invalid id.',
    '3045': 'Apps error: Invalid id.',
    '3046': 'List error: The top-access list got reset.',
    '3047': 'User-Auth error: The user does not exist.',
    '3048': 'User-Auth error: The code needs to be 100 characters long.',
    '3049': 'User-Auth error: The code already exists.',
    '3050': 'User-Auth error: The code does not exist.',
    '3051': 'User-Auth error: The code got denied.',
    '3052': 'User-Auth error: The code is not approved by the user yet.',
    '3053': 'User-Auth error: The name can\'t be empty.',
    '3054': 'User-Auth error: The code is already in use.',
    '3055': 'Chat error: The user needs to exist for at least 7 days to aquire the permission to write in chat.',
    '3056': 'Chat error: The user is blacklisted.',
    '3057': 'Chat error: Missing permissions.',
    '3058': 'Chat error: A user can\'t thank themself, baka.',
    '3059': 'Chat error: Invalid text input.',
    '3060': 'Forum error: The user does not have the permission to access this area.',
    '3061': 'Info error: Deletion of a comment failed.',
    '3062': 'UCP error: Applying changes failed.',
    '3063': 'Anime error: The stream is not accessable for guests.',
    '3064': 'User error: IP authentications needs to be done.',
    '3065': 'Media error: There aren\'t any VAST tags available currently.'
}

export { FATAL_ERRORS, CLIENT_SIDE_ERRORS, SERVER_SIDE_ERRORS }